
server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            NoneAuthFilter

servers:
  auth-service: http://localhost:8080
